evstack/docs

docs/rollkit-stack.md

Closes https://github.com/rollkit/docs/issues/5

clarified sequencer, full node, and light node

---

docs/rollkit-stack.md

docs: add info about dependencies

---

docs/rollkit-stack.md

Closes https://github.com/rollkit/docs/issues/69

Add mempool changes

---

docs/rollkit-stack.md

Closes https://github.com/rollkit/docs/issues/59

docs: describe P2P layer

---

docs/rollkit-stack.md

Add Block Manager Docs

---

docs/rollkit-stack.md

Add State Fraud Proof docs

---

docs/rollkit-stack.md

Adding RPC layer section to docs
Resolves https://github.com/rollkit/docs/issues/66

add rpc layer to docs

---

docs/tutorials/cosmwasm.md
docs/tutorials/ethermint.md
docs/tutorials/gm-world.md
docs/tutorials/recipe-book.md
docs/tutorials/wordle.md

Closes https://github.com/rollkit/docs/issues/43

Use rollkit v0.6.0 in tutorials

---

docs/rollkit-stack.md

Resolves https://github.com/rollkit/docs/issues/88

`rollkit-stack.md` updates

---

docs/intro.md
docs/rollkit-stack.md

Resolves https://github.com/rollkit/docs/issues/99
Resolves https://github.com/rollkit/docs/issues/98
Fixes linting
Adds back introduction, to make it more relatable for the reader

rearrange headings, add deps section, add back intro

---

docs/tutorials/building-and-deploying-a-rollup.md
docs/tutorials/cosmwasm.md
docs/tutorials/ethermint.md
docs/tutorials/gm-world.md
docs/tutorials/hello-world.md
docs/tutorials/local-da-devnet.md
docs/tutorials/recipe-book.md
docs/tutorials/restart-rollkit-rollup.md
docs/tutorials/wordle.md

Resolves https://github.com/rollkit/docs/issues/92

Add local DA guide - a.k.a. Hello World Tutorial

---

docs/scripts/cosmwasm/init.sh
docs/scripts/gm/gm-ci.sh
docs/scripts/gm/init.sh
docs/scripts/hello/init.sh
docs/scripts/recipes/init.sh
docs/scripts/wordle/init.sh
docs/tutorials/building-and-deploying-a-rollup.md
docs/tutorials/cosmwasm.md
docs/tutorials/ethermint.md
docs/tutorials/gm-world.md
docs/tutorials/hello-world.md
docs/tutorials/recipe-book.md
docs/tutorials/restart-rollkit-rollup.md
docs/tutorials/wordle.md

also sentence case for testnet names

doc: add scripts and change tutorial commands

---

docusaurus.config.js
src/pages/index.tsx

Change heading

---

docs/tutorials/building-and-deploying-a-rollup.md

Resolves https://github.com/rollkit/docs/issues/125

Add fuelmint + hyperlane

---

docs/rollkit-stack.md

This PR edits the definition of pure fork-choice rule.

Edit DA layer

---

docs/tutorials/cosmwasm.md
docs/tutorials/gm-world.md
docs/tutorials/hello-world.md
docs/tutorials/recipe-book.md
docs/tutorials/wordle.md

doc: fix scripts using wget

---

docs/tutorials/hello-world.md

Adding example output for the keys and updated the transaction addresses so that it is clear where the information is coming from.

docs/tutorials: add clarification to hello world transaction commands

---

docusaurus.config.js

This removes an extra link to the intro section of docs.

style: remove intro button

---

blog/2023-03-5-sovereign-rollups-on-bitcoin-with-rollkit.mdx
docs/scripts/cosmwasm/init.sh
docs/scripts/gm/gm-ci.sh
docs/scripts/gm/init.sh
docs/scripts/recipes/init.sh
docs/scripts/wordle/init.sh
docs/tutorials/building-and-deploying-a-rollup.md
docs/tutorials/cosmwasm.md
docs/tutorials/ethermint.md
docs/tutorials/gm-world.md
docs/tutorials/hello-world.md
docs/tutorials/recipe-book.md
docs/tutorials/restart-rollkit-rollup.md
docs/tutorials/wordle.md

https://github.com/rollkit/cosmos-sdk/releases/tag/v0.46.7-rollkit-v0.7.1-no-fraud-proofs

Version updates for Blockspace Race

---

docs/intro.md

docs: add prereq of Cosmos SDK

---

docs/rollkit-stack.md
docs/scripts/gm/gm-ci.sh
docs/tutorials/cosmwasm.md
docs/tutorials/gm-world.md
docs/tutorials/recipe-book.md
docs/tutorials/wordle.md
docusaurus.config.js

Update to version 0.7.3 and other updates

---

docs/tutorials/gm-world.md
docs/tutorials/wordle.md

fix: broken links

---

docs/scripts/cosmwasm/init.sh
docs/scripts/gm/gm-ci.sh
docs/scripts/gm/init-local.sh
docs/scripts/gm/init-testnet.sh
docs/scripts/recipes/init.sh
docs/scripts/wordle/init.sh
docs/tutorials/bitcoin.md
docs/tutorials/cosmwasm.md
docs/tutorials/ethermint.md
docs/tutorials/gm-world.md
docs/tutorials/recipe-book.md
docs/tutorials/wordle.md

This removes an unnecessary dependency of md5sum and uses openssl.

docs: remove dependency of md5sum

---

docs/scripts/gm/gm-ci.sh
docs/tutorials/gm-world.md

Resolves #161 
This will be turned into a PR from a draft once there is an image built on `rollkit/local-celestia-devnet`.

deps: change link to local devnet

---

docs/tutorials/gm-world.md

docs: resolve #167, removing links to celestia local devnet on celestia docs

---

docs/tutorials/restart-rollkit-rollup.md

Update restart-rollkit-rollup.md `rollmint` -> `rollkit`

---

docs/tutorials/gm-world.md

This PR reformats the GM tutorial, putting dependencies at the top and fixes a typo.

docs: reformat GM tutorial and fix typo

---

docs/tutorials/cosmwasm.md

docs: fix broken link in cosmwasm

---

docs/tutorials/building-with-rollkit.md
sidebars.js

doc: add building with rollkit page

---

.github/workflows/deploy.yml

testing permissions

---

tutorials/cosmwasm.md
tutorials/gm-world.md
tutorials/recipe-book.md
tutorials/wordle.md

Fix github raw user content links

---

.vitepress/theme/index.ts
.vitepress/theme/style.css

Resolves #221. Banner can be cleared and then reappears after 24 hours, based on browser's `localStorage`.
Preview: https://www.loom.com/share/b6aa173c9a5942ccb53370886daf2af3?sid=64252062-ecf2-40fe-8d6c-a1bfa892c0ca

add banner to show site is under construction

---

scripts/gm/init-full-node.sh
scripts/gm/init-local.sh
tutorials/full-and-sequencer-node.md
tutorials/gm-world.md

These all just happened to fit nicely into this one PR :)
Resolves #240
Resolves #238 
Resolves #189

docs: fix FN + SN setup, deprecate gateway, use programmatic auth token

---

scripts/gm/init-full-node.sh
scripts/gm/init-local.sh
tutorials/full-and-sequencer-node.md
tutorials/gm-world.md

Updates RPC ports on scripts/docs for init-local and init-full-node

fix: gm tutorial

---

learn/pessimistic-rollup-with-a-shared-sequencer.md
learn/rollup-glossary.md
learn/transaction-flow.md
tutorials/cosmwasm.md
tutorials/gm-world.md
tutorials/lazy-sequencing.md
tutorials/recipe-book.md
tutorials/wordle.md

docs: fix typos

---

tutorials/gm-world.md
tutorials/starter-rollup.md

chore: update docker run commands to match #66

---

tutorials/full-and-sequencer-node.md
tutorials/gm-world.md

docs: update docker cmd for rc12

---

tutorials/gm-world.md

Updates tutorial to match API for v0.11.0-rc15. To be made live when devnet & rollkit are bumped to compat with rc15

chore [draft]: match API for v0.11.0-rc15

---

tutorials/gm-world.md
tutorials/recipe-book.md
tutorials/starter-rollup.md
tutorials/wordle.md

chore: bump to rollkit v0.10.5

---

.vitepress/config.ts

Mirrors https://github.com/celestiaorg/docs/pull/1191 on celestia docs. This allows the use of a sitemap with chatbase (rollbot), instead of using a crawler to index site structure, which double-indexes pages.

feat: add sitemap

---

.vitepress/theme/style.css

https://www.loom.com/share/0af7337e59e24e13a48e8ea996948e46?sid=92c1a17b-2e20-42d1-874e-70c20440a2a9

style: test blue

---

.vitepress/config.ts

fix range linking

---

tutorials/wordle.md

Closes https://github.com/rollkit/rollkit/issues/1767

fix: add kurtosis to wordle
